'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const adminHtml = fs.readFileSync(path.join(root, 'public', 'admin.html'), 'utf8');
const personelHtml = fs.readFileSync(path.join(root, 'public', 'personel.html'), 'utf8');
const adminJs = fs.readFileSync(path.join(root, 'public', 'assets', 'admin.js'), 'utf8');
const personelJs = fs.readFileSync(path.join(root, 'public', 'assets', 'personel.js'), 'utf8');
const adminCss = fs.readFileSync(path.join(root, 'public', 'assets', 'admin.css'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const geteinvoices = fs.readFileSync(path.join(root, 'lib', 'atak-geteinvoices.js'), 'utf8');
const faturaHtml = fs.readFileSync(path.join(root, 'public', 'fatura.html'), 'utf8');
const faturaJs = fs.readFileSync(path.join(root, 'public', 'assets', 'fatura.js'), 'utf8');

assert.match(adminHtml, /data-customer-action="invoice"/);
assert.match(adminHtml, /id="customerHubTabs"/);
assert.match(adminHtml, /data-customer-pane="invoice"/);
assert.match(adminHtml, /Fatura geçmişi/);
assert.match(adminHtml, /data-customer-pane="sms"/);
assert.match(adminHtml, /id="salesCustomerSelect"/);
assert.match(adminHtml, /id="salesCustomerInfo"/);
assert.match(adminHtml, /id="salesOpenCustomerProfile"/);
assert.match(adminJs, /function openSalesCustomerProfile/);
assert.match(adminHtml, /#salesCenter\[data-pos-step="1"\] \.sales-products-panel\.pos-step-visible/);
assert.doesNotMatch(adminHtml, /id="salesCustomerRail"/);
assert.doesNotMatch(adminHtml.slice(adminHtml.indexOf('id="salesCenter"'), adminHtml.indexOf('id="mySalesReport"')), /id="salesHub"/);
assert.match(adminHtml, /data-go="invoiceCenter"/);
assert.match(adminHtml, /<b>FATURALAR<\/b>/);
assert.match(personelHtml, /id="salesCustomerSelect"/);
assert.match(personelHtml, /id="salesOpenCustomerProfile"/);
assert.doesNotMatch(personelHtml, /id="salesCustomerRail"/);
assert.match(personelHtml, /id="customersCard"/);
assert.match(personelHtml, /id="payCustomerBox"/);

assert.match(adminJs, /function setCustomerHubPane/);
assert.match(adminJs, /function issueCustomerSaleInvoice/);
assert.match(adminJs, /data-customer-action="invoice"/);
assert.doesNotMatch(adminJs, /function fillSalesCustomerRail/);
assert.doesNotMatch(adminJs, /function fillSalesHubCard/);
assert.match(personelJs, /function openPersonelCustomers/);
assert.match(personelJs, /function renderPayInvoiceBox/);
assert.match(personelJs, /FATURA KES/);
assert.match(adminCss, /\.customer-hub-tabs/);
assert.match(adminCss, /\.customer-invoice-btn/);

assert.match(faturaHtml, /id="invDateFrom"/);
assert.match(faturaHtml, /id="invDealer"/);
assert.match(faturaHtml, /Rapid360 web servisi/);
assert.doesNotMatch(faturaHtml, /Kesilmeyen/);
assert.match(faturaJs, />Kes</);
assert.match(faturaJs, /invoiceKeepPending/);
assert.match(server, /pendingInvoices:/);
assert.match(server, /6\.3\.274-fatura/);
assert.match(server, /function handleAtakGetEInvoices/);
assert.match(geteinvoices, /const isReturn = isReturnRow\(row, sale\)/);
assert.match(geteinvoices, /FaturaAsama: isReturn \? 'IADE' : 'NORMAL'/);
assert.match(geteinvoices, /function dealerIdMatchesAtak/);
assert.doesNotMatch(adminJs, /lib\/atak-geteinvoices/);

console.log('customer-hub-ui.test.js ok');
