'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const adminHtml=fs.readFileSync(path.join(root,'public','admin.html'),'utf8');
const adminJs=fs.readFileSync(path.join(root,'public','assets','admin.js'),'utf8');
assert.match(server,/require\('\.\/lib\/staff-email'\)/);
assert.match(server,/app\.get\('\/web-api\/admin\/staff-emails'/);
assert.match(adminHtml,/id="staffEmailPanel"/);
assert.doesNotMatch(adminHtml,/id="staffMailFillBtn"/);
assert.match(adminHtml,/id="staffMailSendPassBtn"/);
assert.match(adminJs,/\/web-api\/admin\/staff-emails/);
assert.match(adminJs,/\/web-api\/admin\/staff-send-login/);
assert.match(server,/app\.post\('\/web-api\/admin\/staff-send-login'/);
assert.doesNotMatch(adminJs,/fillMissing:true/);
const sendBlock=server.slice(server.indexOf("app.post('/web-api/admin/staff-send-login'"));
const mailAt=sendBlock.indexOf('await sendAppMail');
const hashAt=sendBlock.indexOf('user.passwordHash=hashPassword(password)');
assert.ok(mailAt>=0&&hashAt>mailAt,'şifre hash mail gittikten sonra yazılmalı');
assert.match(adminJs,/Şifre API sunucuda yok/);
console.log('staff-email-ui.test.js ok');
