'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', 'public', 'vitrin');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const js = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const deploy = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'vps-deploy-vitrin.sh'), 'utf8');
const drop = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'vps-drop-public-admin.sh'), 'utf8');
const adminHtml = fs.readFileSync(path.join(__dirname, '..', 'public', 'admin.html'), 'utf8');
const adminJs = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'admin.js'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');

assert.match(html, /Atak Home/);
assert.match(html, /searchInput/);
assert.match(html, /cartBtn/);
assert.doesNotMatch(html, /href="\/personel"/);
assert.doesNotMatch(html, /web-admin/);
assert.match(css, /--blue:#0a4d94/);
assert.match(js, /web-api\/public/);
assert.match(js, /Evinizi sadece döşemeyin/);
assert.match(js, /#\/urunler/);
assert.match(js, /atakShopCart/);
assert.match(deploy, /Do not copy into commerce/);
assert.match(deploy, /location \/uploads\//);
assert.match(deploy, /pm2 restart atak/);
assert.doesNotMatch(deploy, /pm2 restart atakhome-commerce/);
assert.doesNotMatch(deploy, /vps-fix\.sh/);
assert.match(drop, /return 302 https:\/\/atakhome\.com\.tr\//);
assert.match(adminHtml, /data-tab="webSite"/);
assert.match(adminHtml, /https:\/\/atakhome\.com\.tr/);
assert.doesNotMatch(adminHtml, /beta\.atakhome\.com\.tr/);
assert.match(adminJs, /function renderWebSite/);
assert.match(adminJs, /\/web-api\/admin\/site-settings/);
assert.match(server, /function publicProduct/);
assert.match(server, /app\.post\('\/web-api\/admin\/site-settings'/);
assert.doesNotMatch(server.split("app.get('/web-api/public'")[1].slice(0, 800), /purchasePrice/);
console.log('vitrin-public.test.js ok');
